spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect